import { GetStaticProps } from "next";
import Head from "next/head";
import Layout from "../../components/Layout";
import BlogCard from "../../components/BlogCard";
import Link from "next/link";
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { postPath, postFilePaths } from "../../lib/mdx";

interface BlogProps {
	posts: {
		content: string;
		dataStringify: {
			title: string;
			description: string;
			seoTitle: string;
			isPublished: boolean;
			publishedOn: Date;
			author: string;
			coverImage: string;
		};
		filePath: string;
	}[];
	// title: string;
	// path: string;
}

const Index: React.FC<BlogProps> = ({ posts }) => {
	return (
		<Layout>
			<Head>
				<title>Blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* <div className="mr-20 font-semibold text-4xl">
				<h1>Our Latest Blogs</h1>
			</div> */}
			<div className="flex flex-wrap justify-between ">
				{posts.map((post) => (
					<Link as={`/blog/${post.filePath.replace(/\.mdx?$/, "")}`} href="/">
						<div key={post.filePath}>
							<BlogCard
								title={post.dataStringify.title}
								publishedOn={post.dataStringify.publishedOn}
								coverImage={post.dataStringify.coverImage}
							/>
						</div>
					</Link>
				))}
			</div>
		</Layout>
	);
};

export const getStaticProps: GetStaticProps = async (context) => {
	const posts = postFilePaths.map((filePath) => {
		const source = fs.readFileSync(path.join(postPath, filePath));
		const { content, data } = matter(source);
		// console.log("content", content, "data", data);
		const dataStringify = JSON.parse(JSON.stringify(data));
		return {
			content,
			dataStringify,
			filePath,
		};
	});
	return {
		props: {
			posts,
		},
	};
};

export default Index;
