import { GetStaticProps } from "next";
import Head from "next/head";
import Link from "next/link";
import InstaCard from "../components/InstaCard";
import Layout from "../components/Layout";

interface FeedProps {
	postList: {
		data: {
			id: string;
			permalink: string;
			media_url: string;
		}[];
	};
}

const Feed: React.FC<FeedProps> = ({ postList }) => {
	return (
		<Layout>
			<Head>
				<title>Aviate coders</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="mr-20 font-semibold text-3xl mb-4  ">
				<h1>Instagram Feed</h1>
			</div>
			<div className="flex flex-wrap  ">
				{postList.data.slice(0, 9).map((post) => (
					<Link as={`${post.permalink}`} href={`${post.permalink}`}>
						<a>
							<div key={post.id} className="h-full">
								<InstaCard
									id={post.id}
									permalink={post.permalink}
									media_url={post.media_url}
								/>
							</div>
						</a>
					</Link>
				))}
			</div>
		</Layout>
	);
};

export const getStaticProps: GetStaticProps = async (context) => {
	const res = await fetch(
		`https://graph.instagram.com/me/media?fields=id,permalink,media_url&access_token=${process.env.INSTAGRAM_ACCESS_KEY}`
	);

	const data = await res.json();

	// console.log(data);

	const postList = data;

	// console.log(postList);
	return {
		props: {
			postList,
		},
	};
};

export default Feed;
