import { GetStaticProps } from "next";
import Head from "next/head";
import Link from "next/link";
import Layout from "../components/Layout";
import Image from "next/image";
import landingPage from "../public/landingPage.png";
import BlogCard from "../components/BlogCard";
import InstaCard from "../components/InstaCard";
import { getPosts } from "../lib/mdx";
import { Instagram, Twitter } from "react-feather";

interface HomeProps {
	posts: {
		content: string;
		data: {
			title: string;
			description: string;
			seoTitle: string;
			isPublished: boolean;
			publishedOn: Date;
			author: string;
			coverImage: string;
			category: string;
		};
		filePath: string;
		timeForReading: string;
	}[];
	postList: {
		data: {
			id: string;
			permalink: string;
			media_url: string;
		}[];
	};
}

const Home: React.FC<HomeProps> = ({ posts, postList }) => {
	const publishedPosts = posts.filter((post) => post.data.isPublished === true);
	const datePublish = publishedPosts.map((date) => date.data.publishedOn);
	const sortedPosts = publishedPosts
		.slice()
		.sort(
			(a, b) =>
				new Date(b.data.publishedOn).valueOf() -
				new Date(a.data.publishedOn).valueOf()
		);

	const getTopLatestPosts = sortedPosts.slice(0, 6);

	return (
		<Layout>
			<Head>
				<title>Aviate coders</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="grid grid-cols-2 gap-8 items-center justify-center">
				<div className="mr-20 font-semibold text-5xl">
					<h1>Aviating Your Efficiency To Code</h1>
					<div className="flex items-center mt-10">
						<button className="bg-[#1E2E46] hover:bg-[#EFF0F2] hover:text-[#1E2E46] text-white font-bold py-2 px-4 rounded text-lg">
							Subscribe
						</button>
						<div className="ml-5">
							<Link href="https://instagram.com/aviatecoders">
								<a>
									<Instagram />
								</a>
							</Link>
						</div>
						<div className="ml-5">
							<Link href="https://twitter.com/aviatecoders">
								<a>
									<Twitter />
								</a>
							</Link>
						</div>
					</div>
				</div>
				<div className="justify-self-center">
					<Image
						src={landingPage}
						alt="landing page"
						width={600}
						height={500}
					/>
				</div>
			</div>
			<div className="mr-20 font-semibold text-3xl mb-4  ">
				<h1>Our Latest Blogs</h1>
			</div>
			<div className="flex flex-wrap  ">
				{getTopLatestPosts.map((post) => (
					<Link
						as={`/${post.data.category}/${post.filePath.replace(
							/\.mdx?$/,
							""
						)}`}
						href={`/${post.data.category}/${post.filePath.replace(
							/\.mdx?$/,
							""
						)}`}
					>
						<a>
							<div key={post.filePath} className="h-full">
								<BlogCard
									title={post.data.title}
									publishedOn={post.data.publishedOn}
									coverImage={post.data.coverImage}
									timeForReading={post.timeForReading}
								/>
							</div>
						</a>
					</Link>
				))}
			</div>
			<div className="mr-20 font-semibold text-3xl mb-4 mt-5 ">
				<h1>Instagram Feed</h1>
			</div>
			<div className="flex flex-wrap  ">
				{postList.data.slice(0, 6).map((post) => (
					<Link as={`${post.permalink}`} href={`${post.permalink}`}>
						<a>
							<div key={post.id} className="h-full">
								<InstaCard
									id={post.id}
									permalink={post.permalink}
									media_url={post.media_url}
								/>
							</div>
						</a>
					</Link>
				))}
			</div>
		</Layout>
	);
};

export const getStaticProps: GetStaticProps = async (context) => {
	const posts = getPosts();
	const res = await fetch(
		`https://graph.instagram.com/me/media?fields=id,permalink,media_url&access_token=${process.env.INSTAGRAM_ACCESS_KEY}`
	);

	const data = await res.json();

	const postList = data;

	return {
		props: {
			posts,
			postList,
		},
	};
};

export default Home;
